src/objects/Assessment__c.object
<CustomObject>
    <fields>
        <fullName>Review_Date__c</fullName>
        <label>Review Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Review_Status__c</fullName>
        <label>Review Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>In Process</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Deferred</fullName>
                </value>
                <value>
                    <fullName>Approved Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Review_Summary__c</fullName>
        <description>Executive summary of the review.</description>
        <label>Review Summary</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Review_Type__c</fullName>
        <label>Review Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>tech_review_deep_dive</fullName>
                    <label>Technical Review (Deep Dive)</label>
                </value>
                <value>
                    <fullName>Technical Review (periodic)</fullName>
                </value>
                <value>
                    <fullName>Financial_Assessment</fullName>
                    <label>Financial Assessment</label>
                </value>
                <value>
                    <fullName>Business Assessment</fullName>
                </value>
                <value>
                    <fullName>Legal Assessment</fullName>
                </value>
                <value>
                    <fullName>Governance</fullName>
                </value>
                <value>
                    <fullName>Technology Review (Prospect)</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Human Resources</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Grade__c</fullName>
        <description>Used to override the Grade on the assessment.</description>
        <inlineHelpText>Used to override the Grade on the assessment.</inlineHelpText>
        <label>Total Grade</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Due Diligence Checklist</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Due Diligence Checklist Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Due Diligence Checklists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/review_item__c.object
<CustomObject>
    <description>A list of all technology assets that are part of an initial technology due dilligence process.</description>
    <fields>
        <fullName>Assessment__c</fullName>
        <label>Due Diligence Checklist Number</label>
        <referenceTo>Assessment__c</referenceTo>
        <relationshipLabel>Review Items</relationshipLabel>
        <relationshipName>Review_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Assets_Needed__c</fullName>
        <description>This is the list of assets need for the review item. If left blank, the users can provide any documentation they deem fit that answers the review item.</description>
        <inlineHelpText>This is the list of assets need for the review item. If left blank, the users can provide any documentation they deem fit that answers the review item.</inlineHelpText>
        <label>Assets Needed</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Item_Category_Description__c</fullName>
        <label>Item Category Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Item_Category__c</fullName>
        <defaultValue>&quot;other&quot;</defaultValue>
        <label>Item Category</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item_Description__c</fullName>
        <label>Item Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Review_Date__c</fullName>
        <description>Date the documentation was reviewed by the fund tech team.</description>
        <label>Review Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Review_Item_Name__c</fullName>
        <label>Review Item Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Review Item</label>
    <nameField>
        <displayFormat>RI-{0000000}</displayFormat>
        <label>Review Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Review Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/NewTechnicalReview.cls
public class NewTechnicalReview {
  @InvocableMethod(label='Insert Technical Assets' description='Inserts the technical assets related to a particualr account.')
    public static void insertTechReviewItems(List<Id> reviewIDs){
        
        /*List<Assessment__c> reviews = [select id, Name, Review_Date__c, Review_Status__c, Review_Summary__c, Review_Type__c, Total_Grade__c from Assessment__c where Assessment__c.Id in : reviewIDs];
        List<review_item_meta__mdt> reviewItems = [select id, 	MasterLabel , DeveloperName, Rvw_type__c, review_Category__c, Category_Description__c, Item_Assets__c, Item_Description__c from review_item_meta__mdt];
        
        
       	for (Assessment__c review : reviews) {
            if (review.Review_Type__c == 'Technical Review (initial)') {
                
                for (review_item_meta__mdt r:reviewItems) {
                	review_item__c ri = new review_item__c();
                    ri.Assessment__c = review.Id;
                    ri.Assets_Needed__c = r.Item_Assets__c;
                    ri.Item_Category__c = r.review_Category__c;
                    ri.Item_Category_Description__c = 	r.Category_Description__c;
                    ri.Item_Description__c = r.Item_Description__c;
                    ri.Review_Item_Name__c = r.MasterLabel;
                    insert ri;
                    }
                
                  
            }
      
		}
 */
    
    
    }
}