src/objects/Assessment__c.object
<CustomObject>
    <fields>
        <fullName>Review_Date__c</fullName>
        <label>Review Date</label>
        <type>Date</type>
    </fields>
    <label>Due Diligence Checklist</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Due Diligence Checklist Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Due Diligence Checklists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/review_item__c.object
<CustomObject>
    <description>A list of all technology assets that are part of an initial technology due dilligence process.</description>
    <fields>
        <fullName>Assessment__c</fullName>
        <label>Due Diligence Checklist Number</label>
        <referenceTo>Assessment__c</referenceTo>
        <relationshipLabel>Review Items</relationshipLabel>
        <relationshipName>Review_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Assets_Needed__c</fullName>
        <description>This is the list of assets need for the review item. If left blank, the users can provide any documentation they deem fit that answers the review item.</description>
        <inlineHelpText>This is the list of assets need for the review item. If left blank, the users can provide any documentation they deem fit that answers the review item.</inlineHelpText>
        <label>Assets Needed</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>File_Count__c</fullName>
        <label>File Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Finished__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>When this review item is complete, please check this box to indicate you are finished with it and it&apos;s ready to be reviewed.</inlineHelpText>
        <label>Finished</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Grade_Description__c</fullName>
        <description>Why was that grade given?</description>
        <label>Grade Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Grade_Number__c</fullName>
        <description>This field converts the picklist of Grade to a number value for use in calculations.</description>
        <formula>VALUE(TEXT( Item_Grading__c ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Grade Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Is_Locked__c</fullName>
        <description>Used by the custom Assessment Review Items Lightning component to determine whether the record should be read-only for the current user.</description>
        <formula>$Profile.Name = &quot;Community: Portfolio Company&quot; &amp;&amp; NOT(Assessment__r.Is_Current_User_a_Reviewer__c) &amp;&amp; (ISPICKVAL(Review_Item_Status__c, &quot;In File&quot;) || ISPICKVAL(Review_Item_Status__c, &quot;In Process&quot;) || ISPICKVAL(Review_Item_Status__c, &quot;Complete&quot;))</formula>
        <inlineHelpText>Is the Review Item record read-only for the current user due to Review Item Status?</inlineHelpText>
        <label>Is Locked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Item_Category_Description__c</fullName>
        <label>Item Category Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Item_Category__c</fullName>
        <defaultValue>&quot;other&quot;</defaultValue>
        <label>Item Category</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item_Comments__c</fullName>
        <description>A large area where someone can describe the answer to the question (item description) that is asked.</description>
        <label>Item Comments</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Item_Description__c</fullName>
        <label>Item Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Item_Grading__c</fullName>
        <description>Asset grade: 1 is the worst and 3 is the best.</description>
        <label>Item Grading</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <color>#CC0000</color>
                    <label>1</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <color>#F3D904</color>
                    <label>2</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <color>#009900</color>
                    <label>3</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Review_Date__c</fullName>
        <description>Date the documentation was reviewed by the fund tech team.</description>
        <label>Review Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Review_Item_Name__c</fullName>
        <label>Review Item Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Review_Item_Status__c</fullName>
        <label>Review Item Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>In File</fullName>
                </value>
                <value>
                    <fullName>In Process</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Deferred</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Urgent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Marks whether or not this is an urgent item.</description>
        <inlineHelpText>Marks whether or not this is an urgent item.</inlineHelpText>
        <label>Urgent</label>
        <type>Checkbox</type>
    </fields>
    <label>Review Item</label>
    <nameField>
        <displayFormat>RI-{0000000}</displayFormat>
        <label>Review Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Review Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ReviewItemsListController.cls
public with sharing class ReviewItemsListController {

    @AuraEnabled  
    public static Map<String, List<Review_Item__c>> getRecordsMap(String assessmentId) {
        Map<String, List<Review_Item__c>> recordsMap = new Map<String, List<Review_Item__c>>();
        
        List<Review_Item__c> reviewItems = [
            SELECT
                Id,
                Name,
                Assets_Needed__c,
            	File_Count__c,
            	Item_Comments__c,
                Grade_Number__c,
                Urgent__c,
                Item_Grading__c,
                Grade_Description__c,
            	Assessment__c,
            	Assessment__r.Name,
            	Review_Date__c,
                Item_Category__c,
                Item_Category_Description__c,
                Item_Description__c,
                Finished__c,
                Review_Item_Name__c,
                Review_Item_Status__c
            FROM Review_Item__c
            WHERE Assessment__c = :assessmentId
            ORDER BY Item_Category__c ASC NULLS LAST, Name ASC
        ];

        for (Review_Item__c reviewItem : reviewItems) {
            String category = String.isBlank(reviewItem.Item_Category__c) ? 'Other' : reviewItem.Item_Category__c;
            if (!recordsMap.keySet().contains(category)) {
                recordsMap.put(category, new List<Review_Item__c>());
            }
            recordsMap.get(category).add(reviewItem);
        }

        return recordsMap;
    }

    @AuraEnabled
    public static List<ContentDocument> getFileRecords(Id parentId)
    {   
        List<ContentDocument> files = new List<ContentDocument>();
        List<ContentDocumentLink> fileLinks = [
            SELECT ContentDocumentId 
            FROM ContentDocumentLink 
            WHERE LinkedEntityId = :parentId];

        if (!fileLinks.isEmpty()) { 
            Set<Id> fileIds = new Set<Id>();
            for (ContentDocumentLink fileLink : fileLinks) {
                fileIds.add(fileLink.ContentDocumentId); 
            }        
            files = [
                SELECT Id, Title, FileType 
                FROM ContentDocument 
                WHERE ContentDocument.Id IN :fileIds
                ORDER BY Title
            ];
        }
        return files;
    }

    @AuraEnabled
    public static Boolean isRecordEditable(Id recordId) {
        List<UserRecordAccess> access = [
            SELECT RecordId, HasEditAccess, MaxAccessLevel 
            FROM UserRecordAccess 
            WHERE UserId = :UserInfo.getUserId() 
            AND RecordId = :recordId
        ];

        Review_Item__c reviewItem = [
            SELECT Is_Locked__c
            FROM Review_Item__c
            WHERE Id = :recordId
        ];

        Boolean editable = !access.isEmpty() && access[0].HasEditAccess && !reviewItem.Is_Locked__c;
        return editable;
    }

    @AuraEnabled
    public static Boolean isReviewItemCreateable() {
        // below is the desired method of checking permissions, but it always returns true due to
        // known issue W-2616683 where Apex can't correctly determine the current user's access because 
        // the code runs in system mode. for now using VisualForce workaround as decribed at:
        //   https://success.salesforce.com/issues_view?id=a1p300000008djFAAQ
        // Boolean isCreateable = Schema.describeSObjects(new List<String>{'review_item__c'})[0].isCreateable();
        Boolean isCreateable = new CheckObjectPermissionsInVisualForce('review_item__c').isCreateable();
        System.debug('+++ isCreateable: ' + isCreateable);
        return isCreateable;
    }

    @AuraEnabled
    public static void markRecordFinished(Id recordId) {
        Review_Item__c reviewItem = new Review_Item__c(Id = recordId, Finished__c = true);
        update reviewItem;
    }
    @AuraEnabled
    public static void saveRecord (String RIrec){
        RIrec=RIrec.replace('[','').replaceAll(']','');
        system.debug(RIrec);
        Review_Item__c ri = (Review_Item__c)JSON.deserialize(RIrec,Review_Item__c.class);
        
        update ri;
    }
}