src/objects/Assessment__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>The company that is the subject of the assessment.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Assessments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Review_Type__c</fullName>
        <label>Review Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>tech_review_deep_dive</fullName>
                    <label>Technical Review (Deep Dive)</label>
                </value>
                <value>
                    <fullName>Technical Review (periodic)</fullName>
                </value>
                <value>
                    <fullName>Financial_Assessment</fullName>
                    <label>Financial Assessment</label>
                </value>
                <value>
                    <fullName>Business Assessment</fullName>
                </value>
                <value>
                    <fullName>Legal Assessment</fullName>
                </value>
                <value>
                    <fullName>Governance</fullName>
                </value>
                <value>
                    <fullName>Technology Review (Prospect)</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Human Resources</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reviewer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The person reviewing the assessment. First point of contact in the workflow.</description>
        <inlineHelpText>The person reviewing the assessment. First point of contact in the workflow.</inlineHelpText>
        <label>Reviewer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Second_Reviewer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Second Reviewer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Due_Diligence_Checklists</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Due Diligence Checklist</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Due Diligence Checklist Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Due Diligence Checklists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Assessment_Meta_Data__c.object
<CustomObject>
    <description>All the review item data elements used to construct the different assessment types</description>
    <fields>
        <fullName>Review_Category__c</fullName>
        <label>Review Category</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Review_Type__c</fullName>
        <label>Review Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Business Assessment</fullName>
                </value>
                <value>
                    <fullName>Financial Assessment</fullName>
                </value>
                <value>
                    <fullName>Governance</fullName>
                </value>
                <value>
                    <fullName>Human Resources</fullName>
                </value>
                <value>
                    <fullName>Legal Assessment</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Technical Review (Deep Dive)</fullName>
                </value>
                <value>
                    <fullName>Technical Review (periodic)</fullName>
                </value>
                <value>
                    <fullName>Technology Review (Prospect)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Assessment Meta Data</label>
    <nameField>
        <label>Review Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessment Meta Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Document__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/review_item__c.object
<CustomObject>
    <description>A list of all technology assets that are part of an initial technology due dilligence process.</description>
    <fields>
        <fullName>Assessment__c</fullName>
        <label>Due Diligence Checklist Number</label>
        <referenceTo>Assessment__c</referenceTo>
        <relationshipLabel>Review Items</relationshipLabel>
        <relationshipName>Review_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Item_Category_Description__c</fullName>
        <label>Item Category Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Item_Category__c</fullName>
        <defaultValue>&quot;other&quot;</defaultValue>
        <label>Item Category</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Review_Item_Name__c</fullName>
        <label>Review Item Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Review_Item_Status__c</fullName>
        <label>Review Item Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>In File</fullName>
                </value>
                <value>
                    <fullName>In Process</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Deferred</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Submitter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Submitter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Review_Items1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Template</label>
        <referenceTo>Assessment_Meta_Data__c</referenceTo>
        <relationshipLabel>Review Items</relationshipLabel>
        <relationshipName>Review_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Review Item</label>
    <nameField>
        <displayFormat>RI-{0000000}</displayFormat>
        <label>Review Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Review Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AccountReviewItemsDHTMLXControllerTest.cls
@IsTest
public class AccountReviewItemsDHTMLXControllerTest {
    @IsTest
    private static void test1() {
        Account acc = new Account(Name = 'Canapi');
        insert acc;

        Assessment__c assess = new Assessment__c(Account__c = acc.id,Reviewer__c = userInfo.getUserId(), Second_Reviewer__c = userInfo.getUserId());
        insert assess;

        Assessment_Meta_Data__c amd = new Assessment_Meta_Data__c();
        amd.Review_Type__c = 'test';
        amd.Review_Category__c = 'Bronze';
        amd.Name = 'test';
        insert amd;

        AccountReviewItemsDHTMLXController.setDDtype('Legal Assessment',assess.Id);
        AccountReviewItemsDHTMLXController.getDDtemplates();

        review_item__c ri = new review_item__c(
                Assessment__c = assess.Id, 
                Review_Item_Name__c = 'Bronze 1',
                Item_Category__c = 'Bronze',
                Item_Category_Description__c = 'Bronze items',
                Review_Item_Status__c = 'In File',
                Submitter__c = userInfo.getUserId(),
                Template__c = amd.Id);
            
        insert ri;

        AccountReviewItemsDHTMLXController.GetCatTemplateName('Bronze', assess.Id);
        AccountReviewItemsDHTMLXController.updateCatTemplate('Bronze', 'test', assess.Id);
        AccountReviewItemsDHTMLXController.updateTemplate(ri.Id);
        AccountReviewItemsDHTMLXController.updateAllTemplates(assess.Id);

        
        AccountReviewItemsDHTMLXController.setRIData(ri.id,'test','test','test', 'test', '1','Pending', 'test');
        AccountReviewItemsDHTMLXController.updateReviewItems(new List<review_item__c>{ri});
        List <String> statuses = new List <String>{'Pending'};
        Document__c doc = new Document__c (Name__c='test',Account__c=acc.Id);
        insert doc;

        Review_Items_Controller.LinkDocToRI(ri.Id, doc.Id, 'test');
        AccountReviewItemsDHTMLXController.updatePriorities('newcat,' + ri.Id);

        AccountReviewItemsDHTMLXController.createCategory('someCat', assess.Id);
        AccountReviewItemsDHTMLXController.createReviewItem('name', assess.Id, 'someCat');
        AccountReviewItemsDHTMLXController.GetCategoryData('someCat', assess.Id);
        AccountReviewItemsDHTMLXController.setCatData('someCat', 'test', 'newcatName', assess.Id);


        AccountReviewItemsDHTMLXController.GetReviewItemsList(assess.Id,JSON.serialize(statuses),'');
        AccountReviewItemsDHTMLXController.getRIData(ri.id);
        AccountReviewItemsDHTMLXController.getWrapper(ri.id);
        AccountReviewItemsDHTMLXController.saveRecord(JSON.serialize(ri));
        AccountReviewItemsDHTMLXController.setCompleted(ri.id);

        AccountReviewItemsDHTMLXController.removeJunctionObjectById(String.valueOf(ri.Id) + String.valueOf(doc.Id));
        AccountReviewItemsDHTMLXController.GetAllDDchecklists(acc.Id);
        AccountReviewItemsDHTMLXController.getInitValuesWrapper(acc.Id);
        AccountReviewItemsDHTMLXController.getInitValuesWrapper(assess.Id);
        AccountReviewItemsDHTMLXController.getInitValuesWrapper(null);

        AccountReviewItemsDHTMLXController.removeRIById(ri.Id);
        AccountReviewItemsDHTMLXController.removeCategoryByName('newcatName',assess.Id);
        AccountReviewItemsDHTMLXController.removeDDById(assess.Id);

    }

}