src/objects/Round__c.object
<CustomObject>
    <fields>
        <fullName>Round__c</fullName>
        <label>Series</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Seed</fullName>
                </value>
                <value>
                    <fullName>Series A</fullName>
                </value>
                <value>
                    <fullName>Series B</fullName>
                </value>
                <value>
                    <fullName>Series C</fullName>
                </value>
                <value>
                    <fullName>Series D</fullName>
                </value>
                <value>
                    <fullName>Common Shares</fullName>
                </value>
                <value>
                    <fullName>Options</fullName>
                </value>
                <value>
                    <fullName>Warrants</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                    <default>true</default>
                    <label>Unknown</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Series_Type__c</fullName>
        <label>Series Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Share_Price__c</fullName>
        <label>Share Price</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Target_Company__c</fullName>
        <label>Target Company</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Investment</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Series</label>
    <nameField>
        <displayFormat>Round{00000}</displayFormat>
        <label>Investment Series</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Series</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CapTableDHTMLXControllerTest.cls
@IsTest 
public class CapTableDHTMLXControllerTest {

    
    @IsTest
    private static void testgetCapTableData() {
        account a = new account(name='test');
        insert a;
        
        CapTableDHTMLXController.AllowEditingUpdate(a.Id,true);
        
        Round__c round = new Round__c();
        round.Target_Company__c= a.id;
        round.Series_Type__c='test';
        round.Share_Price__c=1;
        
        CapTableDHTMLXController.saveNewRound(JSON.serialize(round));
        insert round;
        
        CapTableDHTMLXController.setDollarAmount(a.id,round.id,500,'All');
        CapTableDHTMLXController.setDollarAmount(a.id,round.id,500,'Non-Voting');
        CapTableDHTMLXController.setDollarAmount(a.id,round.id,500,'Voting');
        CapTableDHTMLXController.setShares(a.id,round.id,500,'All');
        CapTableDHTMLXController.setShares(a.id,round.id,500,'Voting');
        CapTableDHTMLXController.setShares(a.id,round.id,500,'Non-Voting');

        CapTableDHTMLXController.getCapTableData(a.id,'All','Shares');
        CapTableDHTMLXController.getCapTableData(a.id,'Voting','Dollars');
        CapTableDHTMLXController.getCapTableData(a.id,'Non-Voting','Percentage');
        
        CapTableDHTMLXController.getCapTableData(a.id,'All','Dollars');
        CapTableDHTMLXController.getCapTableData(a.id,'Voting' ,'Shares');
        CapTableDHTMLXController.getCapTableData(a.id,'Non-Voting','Percentage');
        
        CapTableDHTMLXController.getCapTableData(a.id,'All','Percentage');
        CapTableDHTMLXController.getCapTableData(a.id,'Voting','Percentage');
        CapTableDHTMLXController.getCapTableData(a.id,'Non-Voting' ,'Shares');
        CapTableDHTMLXController.setDollarAmount(a.id,round.id,500,'Voting');
        CapTableDHTMLXController.setAllShares(a.id,round.id,500,700);
        system.debug(CapTableDHTMLXController.hasRounds(a.id));
        CapTableDHTMLXController.addShareholder(a.id,'t e s t - 2019',a.id);
        CapTableDHTMLXController.getInvestment(a.id,round.id);
        
        CapTableDHTMLXController.deleteSeries (round.Id);
        CapTableDHTMLXController.deleteShareholder (a.Id,a.Id);
        system.debug(CapTableDHTMLXController.getCommunityAccId());
        
        
       
        
        }
}